version: "3"
services:
  app:
    container_name: "${USERNAME}-dev-ps"
    env_file:
      - "./.env"
    build:
      context: "."
      dockerfile: Dockerfile
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
        - PUBLIC_KEY=${PUBLIC_KEY}
    ports:
      - "${PORT}:22"
    expose:
      - "${PORT}"
